"""create update

Revision ID: 041cdbe32c4c
Revises: 8272b50ff89b
Create Date: 2025-06-01 19:07:45.346560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041cdbe32c4c'
down_revision: Union[str, None] = '8272b50ff89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('about', 'created_at', nullable=True)
    op.alter_column('about', 'updated_at', nullable=True)
    op.alter_column('contact', 'created_at', nullable=True)
    op.alter_column('contact', 'updated_at', nullable=True)
    op.alter_column('experience', 'created_at', nullable=True)
    op.alter_column('experience', 'updated_at', nullable=True)
    op.alter_column('project', 'start_date',
               type_=sa.Date(),
               postgresql_using="start_date::date")
    op.alter_column('project', 'end_date',
               type_=sa.Date(),
               postgresql_using="end_date::date")
    op.alter_column('project', 'created_at', nullable=True)
    op.alter_column('project', 'updated_at', nullable=True)
    op.alter_column('skill', 'created_at', nullable=True)
    op.alter_column('skill', 'updated_at', nullable=True)
    op.alter_column('tool', 'created_at', nullable=True)
    op.alter_column('tool', 'updated_at', nullable=True)
    op.alter_column('training', 'created_at', nullable=True)
    op.alter_column('training', 'updated_at', nullable=True)
    op.alter_column('training', 'start_date',
               type_=sa.Date(),
               postgresql_using="start_date::date")
    op.alter_column('training', 'end_date',
               type_=sa.Date(),
               postgresql_using="end_date::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('training', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('training', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('training', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tool', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('tool', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('skill', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('skill', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('project', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('project', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('project', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('project', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('experience', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('experience', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('contact', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('contact', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('about', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('about', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
