"""last update

Revision ID: 34ddd967a56b
Revises: cd6e53db9c0e
Create Date: 2025-06-01 20:04:07.294447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ddd967a56b'
down_revision: Union[str, None] = 'cd6e53db9c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('skill', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tool', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tool', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('training', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training', 'description_fr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training', 'description_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training', 'description_fr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tool', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tool', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('skill', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
