"""exp edit

Revision ID: 367340d07d67
Revises: e8510f89f03a
Create Date: 2025-06-01 18:10:52.417927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '367340d07d67'
down_revision: Union[str, None] = 'e8510f89f03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'company_name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('experience', 'job_title_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'job_title_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experience', 'company_name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
