"""time update

Revision ID: 8272b50ff89b
Revises: ed43fb78bc38
Create Date: 2025-06-01 18:48:10.335576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8272b50ff89b'
down_revision: Union[str, None] = 'ed43fb78bc38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'start_date',
               existing_type=sa.String(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="start_date::date")
    op.alter_column('experience', 'end_date',
               existing_type=sa.String(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="end_date::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('experience', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
