"""Initial migration

Revision ID: a219faf1010a
Revises: 
Create Date: 2025-05-31 13:16:12.301137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a219faf1010a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('about_me_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('about_me_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_title_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_created_at'), 'about', ['created_at'], unique=False)
    op.create_index(op.f('ix_about_updated_at'), 'about', ['updated_at'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intragram', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('x', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gitHub', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resume', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_created_at'), 'contact', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_updated_at'), 'contact', ['updated_at'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_created_at'), 'experience', ['created_at'], unique=False)
    op.create_index(op.f('ix_experience_updated_at'), 'experience', ['updated_at'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_updated_at'), 'project', ['updated_at'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_created_at'), 'skill', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_updated_at'), 'skill', ['updated_at'], unique=False)
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_created_at'), 'training', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_updated_at'), 'training', ['updated_at'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_created_at'), 'tool', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_updated_at'), 'tool', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_updated_at'), table_name='tool')
    op.drop_index(op.f('ix_tool_created_at'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_training_updated_at'), table_name='training')
    op.drop_index(op.f('ix_training_created_at'), table_name='training')
    op.drop_table('training')
    op.drop_index(op.f('ix_skill_updated_at'), table_name='skill')
    op.drop_index(op.f('ix_skill_created_at'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_project_updated_at'), table_name='project')
    op.drop_index(op.f('ix_project_created_at'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_experience_updated_at'), table_name='experience')
    op.drop_index(op.f('ix_experience_created_at'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_contact_updated_at'), table_name='contact')
    op.drop_index(op.f('ix_contact_created_at'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_about_updated_at'), table_name='about')
    op.drop_index(op.f('ix_about_created_at'), table_name='about')
    op.drop_table('about')
    # ### end Alembic commands ###
