"""resume  edit

Revision ID: e8510f89f03a
Revises: 970d0a69d8d3
Create Date: 2025-06-01 17:41:31.439726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e8510f89f03a'
down_revision: Union[str, None] = '970d0a69d8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('contact', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('resume', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contact', 'resume_url')
    # ### end Alembic commands ###
